//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Report.UI.GridReport {


    public partial class ConflictReportOrion
    {
        
        /// <summary>
        /// refreshButton20131 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Report.Controls.C2013.Grid.RefreshButton2013 refreshButton20131;
        
        /// <summary>
        /// jumpBar1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Report.Controls.C2013.Grid.JumpBar jumpBar1;
    }
}
